### ISSUE TITLE
Make scope of jackson dependencies "compile" rather than "runtime"

### ISSUE THREAD

**Issue by seinecle** [felldo/JEmoji#4]
### Your Question

I use JEmoji in a modular project and my tests don't find the Jackson classes used by JEmoji, because their scope is "runtime" not "compile". Would it be possible to change their scope to "compile"? Thanks!

I could sort it out by manually adding the 3 jackson dependencies in my test classes but that should be unnecessary, it is also a source of error (what when the version of these depds get bumped up, if I forget to refresh the version in my tests this will lead to very murky errors).

**Comment by felldo** [comment]
JEmoji only uses Jackson internally and it is not required to interact with the library. Therefore, there's no reason to expose it (change it to compile).
And this is not best practices due to various reasons. [Gradle](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation) has a good documentation on why this should not be done.

Can you please create a MCVE which shows your issue where it can't find the dependency at runtime?

**Comment by seinecle** [comment]
Sure I understand, just that testing in a multi module environment, the tests were failing because of a class not found exception on these deps.
I am not a specialist but changing to "compile" (in Maven) doesn't expose them in any particular way - except making the lib fully functional to other JPMS modules.
Creating an MVCE is too cumbersome given that the project is pretty large but will try.

**Comment by Vampire** [comment]
Your problem is more, that you try to use a library that is not at all prepared to be used with JPMS on the module path.
If you use it from the classpath, it probably works.
If this library would be made a proper JPMS module, it would also work.
But just using it as automatic module indeed can lead to these problems.

If you for example execute this build:
```plain
./build.gradle.kts
plugins {
    application
    id("org.gradlex.extra-java-module-info") version "1.4"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("net.fellbaum:jemoji:1.1.6")
}

application {
    mainModule = "foo/foo.Foo"
}

extraJavaModuleInfo {
    automaticModule("net.fellbaum:jemoji", "net.fellbaum.jemoji")
}

./settings.gradle.kts
rootProject.name = "foo"

./src/main/java/foo/Foo.java
package foo;

import net.fellbaum.jemoji.EmojiManager;

public class Foo {
    public static void main(String[] args) {
        System.out.println(EmojiManager.getAllEmojis().iterator().next());
    }
}

./src/main/java/module-info.java
module foo {
    requires net.fellbaum.jemoji;
}
```
you get a `ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException` when executing the `run` task.
Now if you change
```groovy
extraJavaModuleInfo {
    automaticModule("net.fellbaum:jemoji", "net.fellbaum.jemoji")
}
```
to
```groovy
extraJavaModuleInfo {
    automaticModule("com.fasterxml.jackson.core:jackson-core", "com.fasterxml.jackson.core")
    automaticModule("com.fasterxml.jackson.databind:jackson-databind", "com.fasterxml.jackson.databind")
    module("net.fellbaum:jemoji", "net.fellbaum.jemoji") {
        exports("net.fellbaum.jemoji")
        requires("com.fasterxml.jackson.core")
        requires("com.fasterxml.jackson.databind")
    }
}
```
the `run` task works perfectly fine.

So what you actually ask for, is making this library a proper JPMS module.

> changing to "compile" (in Maven) doesn't expose them in any particular way

It does. Well, not "expose", but it pollutes the downstream compile classpath in unneeded ways which leads to bad dependency declarations where you use transitive dependencies and / or slower compilation because compile classpaths are bigger than they actually need to be.

> except making the lib fully functional to other JPMS modules.

Not really, maybe in your specific situation. But this library does not even have an automatic module name, so it is most probably a very bad idea to use it on the module path as is anyway.

**Comment by seinecle** [comment]
Wow great explainer thank you!
Up to the maintainer to see whether he'd like to make the lib as a JPMS. If I may push in this direction, this would be greatly appreciated not just by me but by fellow lib maintainers who (will) depend on it and release libs designed as JPMS modules.

**Comment by Vampire** [comment]
I only roughly tested it and don't have time for doing it properly and creating a PR.
But this "simple" change should do everything you need properly.
You just have to properly fill the module info with the necessary statements and maybe add some integration tests that run on Java 9 or newer that actually test the outcome in a JPMS environment.

```patch
diff --git a/lib/build.gradle.kts b/lib/build.gradle.kts
index 19c4403..3bbd437 100644
--- a/lib/build.gradle.kts
+++ b/lib/build.gradle.kts
@@ -34,6 +34,38 @@ plugins {
     id("me.champeau.jmh") version "0.7.1"
 }

+val java9 by sourceSets.creating
+tasks.named<JavaCompile>(java9.compileJavaTaskName) {
+    javaCompiler = javaToolchains.compilerFor {
+        languageVersion = JavaLanguageVersion.of(9)
+    }
+    options.compilerArgumentProviders.add(object : CommandLineArgumentProvider {
+        @get:InputFiles
+        @get:PathSensitive(PathSensitivity.RELATIVE)
+        val mainClassesDirs = sourceSets.main.map { it.output.classesDirs }
+
+        override fun asArguments() = mainClassesDirs
+            .get()
+            .files
+            .map { it.absolutePath }
+            .flatMap {
+                listOf(
+                    "--patch-module",
+                    "net.fellbaum.jemoji=$it"
+                )
+            }
+    })
+}
+
+tasks.jar {
+    manifest {
+        attributes("Multi-Release" to true)
+    }
+    from(java9.output) {
+        into("META-INF/versions/9/")
+    }
+}
+
 repositories {
     mavenCentral()
 }
diff --git a/lib/src/java9/java/module-info.java b/lib/src/java9/java/module-info.java
new file mode 100644
index 0000000..afe35cf
--- /dev/null
+++ b/lib/src/java9/java/module-info.java
@@ -0,0 +1,3 @@
+module net.fellbaum.jemoji {
+    exports net.fellbaum.jemoji;
+}
```

**Comment by felldo** [comment]
@Vampire thank you for the code. It works good so far and the `module-info` file gets bundled in the jar. But I am facing an error when adding the jackson dependency. Any chance you know straight out of the head what's missing? Seems like there is some additional configuration needed to add the dependency to the new java9 source sets
```
C:\Users\user\IdeaProjects\jemoji\lib\src\java9\java\module-info.java:3: error: module not found: com.fasterxml.jackson.databind
    requires transitive com.fasterxml.jackson.databind;
```

**Comment by Vampire** [comment]
```kts
val java9Implementation by configurations.existing {
    extendsFrom(configurations.implementation.get())
}
```

But you mean `requires`, not `requires transitive`.
Former is like `implementation`, latter like `api`.
Actually, usually these should be accordingly used.

**Comment by felldo** [comment]
Yeah, I just forgot to change it back when testing if changing it to transitive throws a different error :)
But thanks alot! Seems to be working so far :)

**Comment by felldo** [comment]
@seinecle Can you confirm that the new version works in your case?

**Comment by seinecle** [comment]
👍 will try today

**Comment by seinecle** [comment]
works great. Thanks a lot. For anyone who wants to see the jemoji lib in action in a JPMS project with tests:

https://github.com/seinecle/umigon-tokenizer
