### ISSUE TITLE
some emoji can not replace

### ISSUE THREAD

**Issue by dyimo** [felldo/JEmoji#6]
### JEmoji version

1.2.0

### Steps to reproduce

        chat = "test👁test"; // "test\uD83D\uDC41test"
        chat = EmojiManager.removeAllEmojis(chat);

### What is expected?

👁 can delete

### What is actually happening?

👁 can not delete

**Comment by felldo** [comment]
Thank you for reporting this issue.
This happens due to the fact that currently only `fully-qualified` emojis are taken into account for all operations. 
I am not sure what the exact reason was why I did it like this but I am going to have another look at it and re-think about it.
May you tell me where or from what platform you got this emoji from? Usually nowadays the `fully-qualified` emojis are used.

**Comment by felldo** [comment]
I have just released a new version `1.3.0` which should be available soon. Now all emojis should be taken into account for all operations in the `EmojiManager`.
